Adjusting DDNSManager conf

diff --git a/usr/bin/chonos-wsl-start b/usr/bin/chonos-wsl-start
--- a/usr/bin/chonos-wsl-start
+++ b/usr/bin/chonos-wsl-start
@@ -1,22 +1,60 @@
 #!/bin/bash
-echo "Cleaning temp files"
-sudo rm /tmp/.embedMAS -rf
-sudo rm /dev/shm/.embedMAS -rf
+echo "Starting ChonOS WSL - Services"
 
-echo "Cleaning temp files"
-sudo /etc/init.d/ssh start
-nohup sudo /usr/bin/chonos-log --start &
-nohup sudo /usr/bin/chonos-task --start &
+echo -n "Cleaning temp files... "
+    sudo rm /tmp/.embedMAS -rf
+    if [ $? -ne 0 ]; then echo "[ERROR]"; exit 1; fi
+    sudo rm /dev/shm/.embedMAS -rf
+    if [ $? -ne 0 ]; then echo "[ERROR]"; exit 1; fi
+    sudo mkdir -p /tmp/.embedMAS
+    if [ $? -ne 0 ]; then echo "[ERROR]"; exit 1; fi
+    sudo mkdir -p /dev/shm/.embedMAS
+    if [ $? -ne 0 ]; then echo "[ERROR]"; exit 1; fi
+echo "[OK]"
 
-sudo /usr/bin/chonosDDNSManager --conf -d `cat /etc/hostname` -u "ddns_user" -t "ddns_token"
-sudo /usr/bin/chonosDDNSManager --update
+echo -n "Starting SSH service... "
+    sudo /etc/init.d/ssh start 1>/dev/shm/.embedMAS/nohup.txt
+    if [ $? -ne 0 ]; then echo "[ERROR]"; exit 1; fi
+echo "[OK]"
 
-sudo /opt/group.chon/lib/tomcat/bin/catalina.sh start
+echo -n "Starting ChonOS Log Manager... "
+    nohup sudo /usr/bin/chonos-log --start 1>/dev/shm/.embedMAS/nohup.txt 2>/dev/shm/.embedMAS/nohup.txt &
+    if [ $? -ne 0 ]; then echo "[ERROR]"; exit 1; fi
+echo "[OK]"
 
+echo -n "Starting ChonOS Task Manager... "
+    nohup sudo /usr/bin/chonos-task --start 1>/dev/shm/.embedMAS/nohup.txt 2>/dev/shm/.embedMAS/nohup.txt &
+    if [ $? -ne 0 ]; then echo "[ERROR]"; exit 1; fi
+echo "[OK]"
+
+echo -n "Starting ChonOS DDNS Manager... "
+    domain=$(cat /opt/group.chon/conf/ddns.conf | cut -d ":" -f 1)
+    if [ $? -ne 0 ]; then echo "[ERROR]"; exit 1; fi
+
+    if [ "$domain" == "WSLINSTALL" ]; then
+        domain=$(date +%s%3N | md5sum | cut -c 1-8)
+        if [ $? -ne 0 ]; then echo "[ERROR]"; exit 1; fi
+    fi
+
+    sudo chonosDDNSManager --conf -d $domain 1>/dev/shm/.embedMAS/nohup.txt 2>/dev/shm/.embedMAS/nohup.txt
+    if [ $? -ne 0 ]; then echo "[ERROR]"; exit 1; fi
+    sudo /usr/bin/chonosDDNSManager --update 1>/dev/shm/.embedMAS/nohup.txt 2>/dev/shm/.embedMAS/nohup.txt
+    if [ $? -ne 0 ]; then echo "[ERROR]"; exit 1; fi
+echo "[OK]"
+
+echo -n "Starting ChonOS SysConfig... "
+    sudo /opt/group.chon/lib/tomcat/bin/catalina.sh start 1>/dev/shm/.embedMAS/nohup.txt 2>/dev/shm/.embedMAS/nohup.txt
+    if [ $? -ne 0 ]; then echo "[ERROR]"; exit 1; fi
+echo "[OK]"
 
 json_ddns=$(chonosDDNSManager --status)
-domain=$(echo $json_ddns | jq -r '.domain')
+    if [ $? -ne 0 ]; then echo "[ERROR retrieving DDNS status]"; exit 1; fi
+
+fqdn=$(echo $json_ddns | jq -r '.domain')
+    if [ $? -ne 0 ]; then echo "[ERROR parsing domain]"; exit 1; fi
+
 local_address=$(echo $json_ddns | jq -r '.localAddress')
+    if [ $? -ne 0 ]; then echo "[ERROR parsing local address]"; exit 1; fi
 
 echo "Welcome to ChonOS WSL!"
-echo "Web console: https://$domain:3270 or https://$local_address:3270"
+echo "Web console: https://$fqdn:3270 or https://$local_address:3270"
